User interface
Ambrosegithub/math-magician pull request #2
Opened 2022-08-08 23:00 UTC by Ambrosegithub

### add basic styling and page structure to the math-magician app

- [ ] add class component
- [ ] page structure
- [ ] basic styling
- [ ] linter's check

2022-08-08 23:56 UTC, Reem-lab requested changes
# Hi @Ambrosegithub, 👋🏻👋🏻 

Good job so far! 🔥🔥🚀🚀
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Great working on the set Up ✅
📌 Descriptive pull request ✅
📌 Good commit messages ✅

## Required Changes ♻️
_Check the comments under the review._

[ REQUIRED ] Kindly delete all the boilerplate files except the `index,html` from the `public` directory since this is one of the reuirements 💯💯 I think you have `favicon.ico` file and `robots.txt`
![image](https://user-images.githubusercontent.com/58553711/183534052-deceb428-754b-4fcb-a4d1-518a380fea20.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-08 23:56 UTC, Reem-lab commented on src/App.js
>  function App() {
- [ ] According to the requirement you shoud use the based class component for  the app.js also since it is required for all the components 🚀✅

![image](https://user-images.githubusercontent.com/58553711/183533668-9898faf9-4584-4243-9c15-e3dc2b86e25a.png)

2022-08-09 07:58 UTC, Ambrosegithub commented on src/App.js
>  function App() {
### Done

2022-08-09 08:05 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @Ambrosegithub👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-09 08:19 UTC, merged